services:
  - type: web
    name: customer-churn-detection
    env: python
    buildCommand: pip install --upgrade pip setuptools && pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
